# Generated by Django 5.2.12 on 2026-04-21 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('stroop', 'Stroop Task'), ('nback', 'N-Back'), ('schulte', 'Schulte Table'), ('kakuro', 'Kakuro')], db_index=True, help_text='Machine-readable task identifier.', max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('description', models.TextField(help_text='Multi-sentence explanation shown in the science panel.')),
                ('brain_regions', models.JSONField(default=list, help_text='e.g. ["dorsolateral prefrontal cortex", "anterior cingulate cortex"]')),
                ('cognitive_domains', models.JSONField(default=list, help_text='e.g. ["selective attention", "inhibitory control"]')),
                ('research_refs', models.JSONField(default=list, help_text='List of {title, authors, year, doi, summary} dicts.')),
                ('icon_name', models.CharField(default='psychology', help_text='Material Symbols icon name for the UI.', max_length=32)),
                ('min_difficulty', models.IntegerField(default=1)),
                ('max_difficulty', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'cognitive task',
                'verbose_name_plural': 'cognitive tasks',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CognitiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('difficulty', models.IntegerField(help_text='Integer difficulty level [1..10] chosen by the RL agent.')),
                ('task_params', models.JSONField(default=dict, help_text='Concrete game parameters derived from the difficulty level.')),
                ('total_trials', models.IntegerField(default=0)),
                ('correct_trials', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('avg_reaction_time_ms', models.FloatField(default=0.0)),
                ('error_breakdown', models.JSONField(default=dict, help_text='e.g. {"interference": 3, "omission": 1, "commission": 0}')),
                ('reward', models.FloatField(blank=True, null=True)),
                ('rl_action', models.IntegerField(blank=True, help_text='Difficulty delta chosen by the agent (-2..+2).', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_sessions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cognitive.cognitivetask')),
            ],
            options={
                'verbose_name': 'cognitive session',
                'verbose_name_plural': 'cognitive sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CognitiveTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_index', models.IntegerField(help_text='0-based order within the session.')),
                ('stimulus', models.JSONField(help_text='Task-specific stimulus description.')),
                ('response', models.JSONField(help_text='Task-specific user response.')),
                ('is_correct', models.BooleanField()),
                ('reaction_time_ms', models.IntegerField(help_text='Milliseconds from stimulus onset to user response.')),
                ('error_type', models.CharField(blank=True, default='', help_text='One of: "interference", "omission", "commission", or "" if correct.', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='cognitive.cognitivesession')),
            ],
            options={
                'verbose_name': 'cognitive trial',
                'verbose_name_plural': 'cognitive trials',
                'ordering': ['session', 'trial_index'],
            },
        ),
        migrations.CreateModel(
            name='RLAgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_weights', models.BinaryField(help_text='Serialised PolicyNet state_dict.')),
                ('value_weights', models.BinaryField(help_text='Serialised ValueNet state_dict.')),
                ('optimizer_state', models.BinaryField(blank=True, help_text='Optional serialised Adam optimiser state.', null=True)),
                ('total_episodes', models.IntegerField(default=0)),
                ('last_reward', models.FloatField(blank=True, null=True)),
                ('last_loss', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rl_states', to='cognitive.cognitivetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rl_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RL agent state',
                'verbose_name_plural': 'RL agent states',
            },
        ),
        migrations.CreateModel(
            name='UserCognitiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_score', models.FloatField(default=50.0)),
                ('working_memory_score', models.FloatField(default=50.0)),
                ('processing_speed_score', models.FloatField(default=50.0)),
                ('problem_solving_score', models.FloatField(default=50.0)),
                ('task_stats', models.JSONField(default=dict, help_text='Per-task aggregates: {"stroop": {"sessions_completed": 12, "current_difficulty": 5, "best_accuracy": 0.95, ...}, ...}')),
                ('total_training_minutes', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user cognitive profile',
                'verbose_name_plural': 'user cognitive profiles',
            },
        ),
        migrations.AddIndex(
            model_name='cognitivesession',
            index=models.Index(fields=['user', 'task', '-started_at'], name='idx_session_user_task_date'),
        ),
        migrations.AlterUniqueTogether(
            name='rlagentstate',
            unique_together={('user', 'task')},
        ),
    ]
