# Generated by Django 5.2.12 on 2026-04-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='physical',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='emotion',
            field=models.JSONField(),
        ),
    ]
