# Generated by Django 5.2.12 on 2026-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_email_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='speciality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
