# Generated by Django 5.2.12 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_studentprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="language",
            field=models.CharField(default="en", max_length=2),
        ),
    ]
