# Generated by Django 5.2.12 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_studentprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="camera_access_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="microphone_access_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
